# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_agent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11query_agent.proto\x12\x0bquery_agent\"\x18\n\x06Prompt\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2G\n\rPromptService\x12\x36\n\x08GetQuery\x12\x13.query_agent.Prompt\x1a\x15.query_agent.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROMPT']._serialized_start=34
  _globals['_PROMPT']._serialized_end=58
  _globals['_RESPONSE']._serialized_start=60
  _globals['_RESPONSE']._serialized_end=88
  _globals['_PROMPTSERVICE']._serialized_start=90
  _globals['_PROMPTSERVICE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
